### ISSUE TITLE
运行没有反应啊大佬，有一个报错贴在下面了

### ISSUE THREAD

**Issue by keyucodefield** [simon300000/bili-api#159]
无法找到模块“bili-api”的声明文件。“c:/Users/yuxin/vtb_f/node_modules/bili-api/index.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/bili-api` (如果存在)，或者添加一个包含 `declare module 'bili-api';` 的新声明(.d.ts)文件

这个怎么bane

**Comment by keyucodefield** [comment]
运行allvideos时报错是这样的
TypeError: Cannot read properties of undefined (reading 'count')
    at Object.get (C:\Users\yuxin\vtb_f\node_modules\bili-api\src\api\data.js:32:63)
    at C:\Users\yuxin\vtb_f\node_modules\relationx\src\index.js:74:75
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by simon300000** [comment]
第一个问题是因为你用了typescript，第二个我还要看看
